#
# Makefile for the unit tests
#
# This makefile can safely be edited; it is not
# used by the automated test system.
#
TOP = ..

# Subdirectories to be build
SUBDIRS = common asm vm

include $(TOP)/build.mk
