<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="sss" tagdir="/WEB-INF/tags"%>
<%@ taglib prefix="sss-admin" tagdir="/WEB-INF/tags/admin"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<sss:html_head
	title="Welcome to the SASE Submission System Administration Configuration Interface" />
<body>
<div id="container">
	<sss:header />
	<div id="lbody" class="lbody">
	<sss-admin:menu />
	<div class="table_container">
	<h1 class="table_heading">List of Configuration Properties</h1>
	<p class="description description_yellow">
		This table contains all global configuration properties of the SASE SUB SYSTEM.
	</p>
	<div id="admin_config_list">
	<!-- Actual table is generated by JavaScript in admin_config.js -->
	</div>
	</div>
	</div>
	<sss:footer />
</div>
</body>
</html>