package at.iaik.teaching.sase.ku2013.protocolAnalysis;

/**
 * Server-side interface of a certificate validation black-box.
 * 
 * This interface exposes the publicly visible server-side functionality of a
 * validation blackbox.
 */
public interface ResourceCheckServer {
  /**
   * Handles a request from the client and generates a response.
   * 
   * @param request
   *          The request byte array to be handled.
   * 
   * @return The response byte generated by the validation server.
   * 
   * @throws ResourceCheckException
   *           may be thrown by the underlying server implementation in case of
   *           unexpected error conditions. This exception will NOT be thrown if
   *           a revoked certificate is detected.
   */
  byte[] handle(byte[] request) throws ResourceCheckException;
}
