#
# Makefile for the unit tests
#
# This makefile can safely be edited; it is not
# used by the automated test system.
#
TOP = ..

# Subdirectories to be build
SUBDIRS = common bigint

#ifdef REFERENCE_C2
TASK_EXTRA_FILES = Makefile
#endif
include $(TOP)/build.mk
