#
# Makefile for the common utility library.
#

# List of source files for the utilitiy library (libutil.a)
#
# TODO: Edit this variable to include all source files required
# to compile your utility library (libutil.a) library. Note that
# the files listed in this make variable MSUT NOT contain a
# "main" function.
#
SOURCES = buffer.c memview.c

# Extra preprocessor macros for building the tiny VM assembler.
#
# This make variable can be used if your program requires
# certain feature test macros to compile. See the feature_test_macros(7)
# manpage for more details. The _GNU_SOURCE macro enables various extension
# to the C99 standard (including functions like strdup, strndup, ...).
DEFINES = _GNU_SOURCE

include util.mk
