#
# Makefile for the common testing library
#
# This makefile can safely be edited; it is not
# used by the automated test system.
#
LIBRARY  = testing
SOURCES  = testrunner.c testallocs.c testdefaults.c testresources.c testgarbage.c
DEFINES  = _GNU_SOURCE

TOP      = ../..
include $(TOP)/build.mk
