///
/// \file
/// \brief Access to embedded resources of the test application.
///
#include "testhelpers.h"

/// \brief Resource lookup function generated by \c bin2res.pl script.
///
/// This function is typically generated with the \c bin2res.pl script,
/// and can be found in \c _resources.c (when the standard resource
/// framework is used)
const void* EmbeddedResourceLookup(size_t *length, const char *name);

//----------------------------------------------------------------------
const void* TestGetResource(size_t *length, const char *name)
{
  const void *data = EmbeddedResourceLookup(length, name);
  CU_ASSERT_PTR_NOT_NULL_FATAL(data);
  return data;
}
